# Generated by Django 4.0.3 on 2022-04-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0004_alter_rating_rate_date_alter_review_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rate_date',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
