# Generated by Django 4.0.3 on 2022-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0005_remove_rating_rate_date_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='artist',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
