# Generated by Django 4.0.3 on 2022-04-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0006_artist_avgrating_artist_count_rating_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='avgRating',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='artist',
        ),
    ]
