# Generated by Django 4.0.2 on 2022-03-08 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=510)),
                ('review_date', models.DateTimeField(default=datetime.datetime.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables_app.artist')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables_app.user')),
            ],
        ),
    ]
