# Generated by Django 4.0.2 on 2022-03-11 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables_app', '0003_rating_rate_date_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
